### ISSUE TITLE
Sync Firestore Collection with Advanced Custom Fields

### ISSUE THREAD

**Issue by vgensw** [dalenguyen/firebase-wordpress-plugin#113]
**Is your feature request related to a problem? Please describe.**
New Feature

**Describe the solution you'd like**
It would be great to have an advanced Synchronisation between WordPress & Firestore to Display content via Page Builders like Elementor. Therefore it would be great to synchronize a Firestore Collection with advanced custom Fields to use these data to work with elementor to display them (eg. collection of online courses and you could style the listing page of all online courses with elementor.

**Describe alternatives you've considered**
Direct integration into elementor (?)

**Which fields does it relate to?**
Firebase Auth, Realtime DB, Firestore, Storage...
Firestore

**Additional context**

**Comment by TheWizardofWikacy** [comment]
Yes, this would make a lot of sense.  Then content could be added like posts are added, instead of just dead data being displayed, with links that go to the entire document just like posts.  I'm pretty sure this can be done using custom scripts, unfortunately when I follow the docs on adding the custom scripts, the server can never find the script.  So there is some error in the plugin.  Have you ever received a reply?

**Comment by dalenguyen** [comment]
This one can be done via filter hooks to add custom data before saving. 

https://firebase-wordpress-docs.readthedocs.io/en/latest/hooks/pro-filters.html#before-saving-post-data-to-firebase
