### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by satya-securemachines** [dalenguyen/firebase-wordpress-plugin#120]
Hi Dale, 

Would it be possible to use the shortcodes from your plug-in in an "elementor" page?

I tried using the shortcode widget in elementor page but does not seem to work.

Could you clarify?

Thanks,
Satya

**Comment by dalenguyen** [comment]
Hi @satya-securemachines, 

Which version of the plugin are you using? 
Which shortcode are you trying to put to Elementor?
Is there any error in the console log? 

Any snapshots would be great.

Thanks,

**Comment by satya-securemachines** [comment]
Hi Dale, 

 

Below is a screen shot. When I publish, cant see anything on the page. 

 

Elementor v3.0.11

 

1.14.0

 



 

Thanks & Regards,

Satya

**Comment by dalenguyen** [comment]
Hi @satya-securemachines, I couldn't see the screenshot. I think you need to do it directly in Github rather than reply the email.

**Comment by satya-securemachines** [comment]
Attached
![1](https://user-images.githubusercontent.com/70796305/95095994-5c734f80-0749-11eb-8d38-35ab9e65bf6e.png)

**Comment by dalenguyen** [comment]
Thank @satya-securemachines, I will check it and get back to you later.

**Comment by dalenguyen** [comment]
I just tried with Elementor v3.011 & IFP v1.16.0 and it works. 

https://wordpress.dalenguyen.me/elementor-301/

Something that you should notice is that you may need to save it and view the page in order to see the shortcode. Or you put that shortcode somewhere else which shows on other places. You can try with other shortcodes to check if it works. 

Let me know how does it go. You can send a test link if it still doesn't work.

**Comment by dalenguyen** [comment]
Hi @satya-securemachines, just want to check if everything is working on your end.

**Comment by dalenguyen** [comment]
I should be fixed now.
