### ISSUE TITLE
Delay in signup time

### ISSUE THREAD

**Issue by bcole2433** [dalenguyen/firebase-wordpress-plugin#121]
**Describe the bug**
There is a long delay between when a user logs in through the FirebaseUI and when the user is redirected after signing (consistently 3 - 8 seconds). If a user refreshes or clicks to another page, the user is signed in through Firebase, but not through Wordpress. This means that the user is logged in on Firebase, but not on Wordpress which causes issues.

**To Reproduce**
1. Go to https://premierlacrosseleague.com/login
2. Login
3. Click to another page right after submitting login page
4. Refresh

**Expected behavior**
If logged in correctly, the user should be redirected. If they go back to the /login page. There should be a Signout button with text indicating that you are already logged in.

**Version**
The version of the plugin. E.g PRO v1.16

**Comment by dalenguyen** [comment]
Thank @bcole2433, It's because it needs to wait for firebase to log in successfully then log in to WordPress. Maybe a loading state can solve the click away behavior. I will take a look at the weekend

In order to let users know if they are logging in or not, you can use the greetings shortcode or a message only for logged in users.

**Comment by dalenguyen** [comment]
The loading state is added in v1.17.0
