### ISSUE TITLE
We are looking to buy your plugin but have some questions around whether we are likely to be able to use it

### ISSUE THREAD

**Issue by eatoutheroes** [dalenguyen/firebase-wordpress-plugin#130]
**Is your feature request related to a problem? Please describe.**

A) We want our customers to be able to make a purchase using woocommerce and then submit the details of the order and quantity into firebase as a document within a collection. Is this possible? The Woocommerce feature just seems to relate to authentication.

B) We also want to be able to create pdf reports of data stored from transactions that take place via the app. Would it be possible to extract data from documents as a list and display them in Wordpress page. Could the data be extracted and put into a PDF?  It's basically for self-billing invoices.

**Describe the solution you'd like**

A) User adds purchase and goes through checkout process using Woocommerce being logged in as the same user as in firebase. The product purchased and quantity is then added to firebase on the success of the transaction.

B) Within the user admin panel create a page that displays a list of transactions that are stored in firebase that are made via the app. These are a list of transactions that we need to make payments against, so I need to be able to show the user a list of transactions and display the relevant data as a pdf that can be downloaded from within the admin panel.

**Describe alternatives you've considered**
I haven't. I am trying to figure out if we can use your application rather than a bespoke api.

**Which fields does it relate to?**
Firebase Auth, Realtime DB, Firestore, Storage...

Firestore

**Additional context**

**Comment by dalenguyen** [comment]
Hi @eatoutheroes, 

The current plugin main support authentication for WooCommerce. In order to submit data to firestore, it can be done via filter hooks. 

https://firebase-wordpress-docs.readthedocs.io/en/latest/hooks/filters.html

For self-billing invoices, the data can be extracted and displayed on the WordPress page. In order to generate the PDF, it will require customization - but it can be done via a custom script.

https://firebase-wordpress-docs.readthedocs.io/en/latest/developer/add-custom-scripts.html

The product purchased can be done via a filter hook like the example above.

Most of the features that you describe can be done by using custom scripts & filter hook. I haven't finished the Woocommerce extension for the plugin. I will keep your questions as input for the extension.

**Comment by dalenguyen** [comment]
Hi @eatoutheroes, how is it going? If it's possible please share the invoice structure in your firebase, I can create a POC for that.

**Comment by dalenguyen** [comment]
The initial version of Woocommerce is added that can support order synchronization. The other tasks can be done via custom codes.

https://firebase-wordpress-docs.readthedocs.io/en/latest/extensions/woocommerce.html
