### ISSUE TITLE
How to integrate firebase database to wordpress

### ISSUE THREAD

**Issue by Indhusuresh** [dalenguyen/firebase-wordpress-plugin#14]
I already have android app in firebase database.
I want to link that to wordpress, to create an web application. please help

**Comment by dalenguyen** [comment]
Hi @Indhusuresh, how you want to integrate it?

**Comment by Indhusuresh** [comment]
I have an Android app, all of the app data are stored in firebase (cloud database). Now I wish to develop a Web application for the same Android app using WordPress. For this, I want to integrate already existing my firebase database to WordPress, so that I can access data from a single source for my Android and web app. And also In future, if I want to make any changes to data, I can make it in firebase and that automatically reflects in both my platforms (Mobile and WEb).

**Comment by Clairyta** [comment]
Hey! That is exactly what I would like to do. I have a database in firebase and I would like to pull the data to wordpress and post as custom elements. is it possible to do that via this app?

**Comment by Clairyta** [comment]
Okay, thank you! Do you know if there is a plugin I could customize? Or could we work together to make it possible?

**Comment by Indhusuresh** [comment]
@dalenguyen @Clairyta Yesss... Is there any way to do it? I dont find any online source to make it possible.

**Comment by dalenguyen** [comment]
Sorry @Indhusuresh @Clairyta, I'm not sure if there are any other plugins that have the functions that you are looking for. Sadly, I'm not working with WordPress and Firebase in the new workplace anymore. It's hard to find time to upgrade this plugin.

**Comment by acelmec** [comment]
Dear, I am creating an Android APP through THUNKABLE using FrameWork with my WEB Page built in WORDPRESS. I needed to know if I can integrate the WORDPRESS user database in FIREBASE, so I could create a LOGIN in the Android APP. Thanks for your help!

**Comment by eldadcaspi** [comment]
As a general concept, I'd suggest to do the following: 
1. Base your integration on Firebase Cloud Function on the Firebase side, and a custom plugin on the wp side. 

2. On firebase, whenever your android in adding/deleting/updating data, catch it with a trigger (https://firebase.google.com/docs/functions/database-events) and simply push the data to wp using the WP rest api or any other preferable mean. On the WP side, listen to the "save_post" action and push any saved/edited data to Firebase using a simple remote post to the Cloud Function endpoint url. 

3. To sync users and their personal data on both clients - for the android app just keep your users login directly to firebase and read/write to fb from there (which will result in triggering the data pushes to your wp users too), and for the wp side -  you don't have to have the wp user login for real to firebase, instead you could create an admin service account on firebase to use on your cloud functions side (that will allow you to read/write everything to everywhere on you fb database regardless to who's logged in to fb) and adjust your requests from wp to fbcf to control the affected users/datas on fb - play "god" with this admin account, that's why it's there for. 

4. to protect your firebase cloud functions endpoints from being abused, add some secret hash string to the data you're sending to fbcl as a basic handshake to validate legitimate requests.

**Comment by dalenguyen** [comment]
Database integration is now possible. Read the userguide: https://firebase-wordpress-docs.readthedocs.io/en/latest/index.html
