### ISSUE TITLE
what is "your-class-name" ??

### ISSUE THREAD

**Issue by arthurahy** [dalenguyen/firebase-wordpress-plugin#179]
hey man.. newbie here
what is "your-class-name" ?
what information do i need to put in there?
i'm sorry for my silly question..

**Comment by dalenguyen** [comment]
Hi @arthurahy, 

it's the name for CSS styling, so you can add custom CSS in order to style the element :)

**Comment by Nashev** [comment]
Could You please rename it to "optional-your-CSS-class-name" in the documentation pages like 
* https://wordpress.org/plugins/integrate-firebase/#how%20can%20i%20show%20data%20for%20a%20not%20logged%20in%20user%3F
* https://github.com/dalenguyen/firebase-wordpress-plugin/blob/master/README.md
etc?

It will clarify this topic in most easy way. Because I also wondered a while what the hell is this...

**Comment by dalenguyen** [comment]
Thanks, @Nashev. That's great suggestion!
