### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by kaiserlct** [dalenguyen/firebase-wordpress-plugin#45]
**Is your feature request related to a problem? Please describe.**

I want my app users to use the forum on WP site to discuss feature and bugs and I want them to use their app firebase credentials. This will show everyone their email as username which has privacy issues.

**Describe the solution you'd like**
I want the username to be taken from a firestore collection as the username on the website.

**Describe alternatives you've considered**

**Additional context**

**Comment by dalenguyen** [comment]
Thanks @kaiserlct for the suggestion. One solution that I can think of is to randomly generate a username for your app users, otherwise, it would require a custom process to access the Firestore then get their username from a specific field, and create a new User in WordPress. By doing this, the process to log in WordPress will take longer than usual which is not an optimal solution.

**Comment by kaiserlct** [comment]
Thanks for your reply; They can still log in with email authentication but all I want is the username to be displayed in the forum pages rather than users emails address.

**Comment by dalenguyen** [comment]
Thanks. Can a have the name of the plugin you are using for the forum? And a photo of how user is displayed on it?

**Comment by kaiserlct** [comment]
The plugin is Asgaros Forum. These are examples of non-firebase create
usernames showing on the forum.

[image: image.png]


Cheers

Kaiser

lifechange.foundation <https://www.lifechange.foundation/>

**Comment by dalenguyen** [comment]
This is fixed in V1.4.0 

https://mailchi.mp/a04e9ca33841/integrate-firebase-pro-happy-changes-v0180-4748270
