### ISSUE TITLE
💡 Support for Custom Taxonomies

### ISSUE THREAD

**Issue by altechzilla** [dalenguyen/firebase-wordpress-plugin#74]
Currently, taxonomies do not get their own collections in Firestore. Can you add an option where taxonomies get pushed too, and then they’re simply connected through IDs with their respective post objects?

**Comment by harshachaitanya** [comment]
+1

**Comment by harshachaitanya** [comment]
This feature will help us a lot. 
If possible can you change the structure of storing categories at firebase collection, why because unable to query posts based on category or tag at Firebase Cloud Firestore collection on the mobile.
if any query to search post based on category/tag at cloud Firestore do let us know.
Can you expedite this feature? we related need this.

![image](https://user-images.githubusercontent.com/35361849/117798484-d4b96a80-b26e-11eb-9b15-da1f0c78353a.png)

**Comment by dalenguyen** [comment]
Thanks @harshachaitanya. I will check this one on the weekend.

**Comment by dalenguyen** [comment]
Hi @harshachaitanya, the purpose is to query posts by categories right? Do you query by name or id?

**Comment by harshachaitanya** [comment]
> Hi @harshachaitanya, the purpose is to query posts by categories right? Do you query by name or id?

Id

**Comment by dalenguyen** [comment]
@altechzilla sorry for the long wait, categories will be added in the next release (tomorrow). 
@harshachaitanya not sure how to structure the categories with id in it. If you have a recommendation on how it should be in order to support query purposes, please create another ticket or discussion. I don't want to spam Altechzilla's inbox 😄

**Comment by harshachaitanya** [comment]
Thanks, @dalenguyen for releasing this feature. 
I come across a minor bug in the flow, it's working for creating & update of category. But when we delete a category it's on delete at firestore side. Can you look into this?

**Comment by harshachaitanya** [comment]
> @altechzilla sorry for the long wait, categories will be added in the next release (tomorrow).
> @harshachaitanya not sure how to structure the categories with id in it. If you have a recommendation on how it should be in order to support query purposes, please create another ticket or discussion. I don't want to spam Altechzilla's inbox 😄

Will create another ticket or discussion regarding this.
